<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Manny Bettencourt (2515997), Kush Bhatia (2498203), Aryan Patel (2494029)">

<title>Global Population Health Trends (1990–2023)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="QTM_350_Final_Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="QTM_350_Final_Project_files/libs/quarto-html/quarto.js"></script>
<script src="QTM_350_Final_Project_files/libs/quarto-html/popper.min.js"></script>
<script src="QTM_350_Final_Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="QTM_350_Final_Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="QTM_350_Final_Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="QTM_350_Final_Project_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="QTM_350_Final_Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="QTM_350_Final_Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="QTM_350_Final_Project_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="QTM_350_Final_Project.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Global Population Health Trends (1990–2023)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Manny Bettencourt (2515997), Kush Bhatia (2498203), Aryan Patel (2494029) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Over the recent decades, population health has increased significantly across the globe as a result of improvements in healthcare, education, and socio-economic status. However, the pace and drivers of these improvements vary widely across regions. The project aims to compare worldwide trends in life expectancy, under-5 mortality, and adolescent fertility from 1990 to 2023 in order to determine how various regions have undergone population health enhancement.</p>
<section id="our-research-addresses-two-main-questions" class="level4">
<h4 class="anchored" data-anchor-id="our-research-addresses-two-main-questions">Our research addresses two main questions:</h4>
<ol type="1">
<li><strong>Which regions have experienced the fastest improvements in population health, and what role did adolescent fertility and child mortality reductions play?</strong></li>
<li><strong>Are reductions in under-5 mortality more strongly associated with improvements in life expectancy than reductions in adolescent fertility</strong>?</li>
</ol>
<p>To address these questions, we analyzed publicly available World Bank data to follow trends over time in key and selected other health indicators. We compared seven key world regions, examining absolute trends as well as interrelationships among various indicators. Additionally, we performed correlation and scatterplot analyses to evaluate the relative strength of associations between child mortality reductions, adolescent fertility declines, and gains in life expectancy.</p>
<p>Through this analysis, we aim to highlight not just where health outcomes have improved the most, but also to better understand the underlying dynamics contributing to these improvements.</p>
</section>
</section>
<section id="data-description" class="level1">
<h1>Data Description</h1>
<section id="introduction-of-the-dataset-and-context" class="level2">
<h2 class="anchored" data-anchor-id="introduction-of-the-dataset-and-context">Introduction of the Dataset and Context</h2>
<p>Our analysis focuses on global population health trends using three key indicators sourced from the World Bank World Development Indicators (WDI) database:</p>
<ul>
<li><p>Life Expectancy at Birth (SP.DYN.LE00.IN)</p></li>
<li><p>Under-5 Mortality Rate (SH.DYN.MORT)</p></li>
<li><p>Adolescent Fertility Rate (SP.ADO.TFRT)</p></li>
</ul>
<p>The dataset provides annual values for over 200 countries and regions across multiple decades, offering a comprehensive view of global health improvements.</p>
<p>We narrowed our analysis to the period from 1990 to 2023 to ensure consistency and reliability across countries. Many regions had incomplete or less standardized reporting prior to 1990, and focusing on this period allows us to capture recent and more comparable trends in global health progress.</p>
</section>
<section id="data-merging-steps" class="level2">
<h2 class="anchored" data-anchor-id="data-merging-steps">Data Merging Steps</h2>
<ul>
<li><p><strong>Initial Pull</strong>: We pulled the three indicators separately through the <code>wbdata</code> API, obtaining raw data tables for life expectancy, under-5 mortality, and adolescent fertility.</p></li>
<li><p><strong>Reshape and Combine</strong>: Each table was reshaped to have a consistent structure (<code>country</code>, <code>date</code>, <code>value</code>) and renamed appropriately.</p></li>
<li><p><strong>Merge Process</strong>: Using SQL, the three tables were merged into a single master dataset by matching on <code>country</code> and <code>date</code>, ensuring that only rows with complete data for all three indicators were included.</p></li>
<li><p><strong>Storage</strong>: The merged dataset was stored in an SQLite in-memory database for easier querying and preprocessing.</p></li>
</ul>
</section>
<section id="data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h2>
<ul>
<li><p><strong>Missing Values</strong>: Rows with missing values in any of the three indicators were removed.</p></li>
<li><p><strong>Date Filtering</strong>: Only observations between 1990 and 2023 were kept.</p></li>
<li><p><strong>Aggregation</strong>: Countries were aggregated into seven major global regions for analysis consistency.</p></li>
<li><p><strong>Transformation</strong>: Data was reshaped to create new variables such as percentage changes between 1990 and 2023.</p></li>
</ul>
<p>The following Python code was used for merging:</p>
<div id="3d9b7432" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> wbdata</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Set indicators</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>indicators <span class="op">=</span> {</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SP.DYN.LE00.IN'</span>: <span class="st">'life_expectancy'</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SH.DYN.MORT'</span>: <span class="st">'under5_mortality_rate'</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SP.ADO.TFRT'</span>: <span class="st">'adolescent_fertility_rate'</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Fetch data (NO date filter)</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> wbdata.get_dataframe(indicators)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Reset index</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.reset_index()</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Drop rows with missing values</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna()</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Load into SQLite in-memory database</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>conn <span class="op">=</span> sqlite3.<span class="ex">connect</span>(<span class="st">':memory:'</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>df.to_sql(<span class="st">'population_data'</span>, conn, index<span class="op">=</span><span class="va">False</span>, if_exists<span class="op">=</span><span class="st">'replace'</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># 6. Create cleaned table</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>conn.execute(<span class="st">"""</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="st">CREATE TABLE cleaned_population_data AS</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="st">    country,</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="st">    date,</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="st">    life_expectancy,</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="st">    under5_mortality_rate,</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="st">    adolescent_fertility_rate</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="st">FROM</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="st">    population_data</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="st">    life_expectancy IS NOT NULL</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="st">    AND under5_mortality_rate IS NOT NULL</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="st">    AND adolescent_fertility_rate IS NOT NULL</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>conn.commit()</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="co"># 7. Descriptive stats</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>stats_query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="st">    AVG(life_expectancy) AS avg_life_expectancy,</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="st">    MIN(life_expectancy) AS min_life_expectancy,</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="st">    MAX(life_expectancy) AS max_life_expectancy,</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="st">    AVG(under5_mortality_rate) AS avg_under5_mortality,</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="st">    MIN(under5_mortality_rate) AS min_under5_mortality,</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="st">    MAX(under5_mortality_rate) AS max_under5_mortality,</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="st">    AVG(adolescent_fertility_rate) AS avg_adolescent_fertility,</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="st">    MIN(adolescent_fertility_rate) AS min_adolescent_fertility,</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="st">    MAX(adolescent_fertility_rate) AS max_adolescent_fertility</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="st">FROM</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="st">    cleaned_population_data</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>stats_result <span class="op">=</span> pd.read_sql_query(stats_query, conn)</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats_result)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="co"># 8. Group by country</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>grouped_query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="st">    country,</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="st">    AVG(life_expectancy) AS avg_life_expectancy,</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="st">    AVG(under5_mortality_rate) AS avg_under5_mortality_rate,</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="st">    AVG(adolescent_fertility_rate) AS avg_adolescent_fertility_rate</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="st">FROM</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="st">    cleaned_population_data</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="st">GROUP BY</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="st">    country</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="st">    avg_life_expectancy DESC</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>grouped_result <span class="op">=</span> pd.read_sql_query(grouped_query, conn)</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grouped_result.head())</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="co"># Query the cleaned table into a DataFrame</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>cleaned_df <span class="op">=</span> pd.read_sql_query(<span class="st">"SELECT * FROM cleaned_population_data"</span>, conn)</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="co"># Now cleaned_df is a normal DataFrame you can manipulate</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cleaned_df.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   avg_life_expectancy  min_life_expectancy  max_life_expectancy  \
0            65.252508               10.989               86.372   

   avg_under5_mortality  min_under5_mortality  max_under5_mortality  \
0             71.114946                   1.4                 767.4   

   avg_adolescent_fertility  min_adolescent_fertility  \
0                 72.515224                     0.512   

   max_adolescent_fertility  
0                   229.604  
                     country  avg_life_expectancy  avg_under5_mortality_rate  \
0                     Monaco            82.924282                   5.166667   
1                    Andorra            82.030308                   7.423077   
2                 San Marino            81.448641                   6.107692   
3                  Euro area            79.545286                   5.312769   
4  Post-demographic dividend            78.542056                   6.698336   

   avg_adolescent_fertility_rate  
0                      14.336128  
1                       8.424590  
2                       3.891615  
3                      10.007935  
4                      20.049102  
                       country  date  life_expectancy  under5_mortality_rate  \
0  Africa Eastern and Southern  2023        65.146291              53.806252   
1  Africa Eastern and Southern  2022        64.487020              56.644907   
2  Africa Eastern and Southern  2021        62.979999              57.140506   
3  Africa Eastern and Southern  2020        63.766484              58.911653   
4  Africa Eastern and Southern  2019        63.857261              60.658078   

   adolescent_fertility_rate  
0                  92.305668  
1                  93.379389  
2                  94.659513  
3                  95.741339  
4                  97.189787  </code></pre>
</div>
</div>
</section>
<section id="summary-of-key-variables" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-key-variables">Summary of Key Variables</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>country</code></td>
<td>Name of the country or region</td>
</tr>
<tr class="even">
<td><code>date</code></td>
<td>Year of observation</td>
</tr>
<tr class="odd">
<td><code>life_expectancy</code></td>
<td>Life expectancy at birth (in years)</td>
</tr>
<tr class="even">
<td><code>under5_mortality_rate</code></td>
<td>Mortality rate under age 5 (per 1,000 live births)</td>
</tr>
<tr class="odd">
<td><code>adolescent_fertility_rate</code></td>
<td>Births per 1,000 women aged 15–19</td>
</tr>
<tr class="even">
<td><code>life_expectancy_pct_change</code></td>
<td>Percent change in life expectancy between 1990 and 2023</td>
</tr>
<tr class="odd">
<td><code>under5_mortality_pct_change</code></td>
<td>Percent change in under-5 mortality between 1990 and 2023</td>
</tr>
<tr class="even">
<td><code>adolescent_fertility_pct_change</code></td>
<td>Percent change in adolescent fertility rate between 1990 and 2023</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="data-analysis" class="level1">
<h1>Data Analysis</h1>
<section id="initial-preparation-and-region-selection" class="level2">
<h2 class="anchored" data-anchor-id="initial-preparation-and-region-selection">Initial Preparation and Region Selection</h2>
<p>We began by refining the cleaned dataset:</p>
<ul>
<li><p>The date column was converted to an integer type to ensure proper time-based filtering and plotting.</p></li>
<li><p>We filtered the data to focus on seven major global regions:</p>
<ul>
<li>East Asia &amp; Pacific, Europe &amp; Central Asia, Latin America &amp; Caribbean, Middle East &amp; North Africa, North America, South Asia, and Sub-Saharan Africa.</li>
</ul></li>
</ul>
<p>This selection was made to focus on broad global patterns while maintaining sufficient regional diversity.</p>
<div id="14b81c8a" class="cell tbl-cap-location-top" data-tbl-colwidths="[0.15,0.15,0.15,0.15,0.15,0.15,0.15]" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">life_expectancy</th>
<th data-quarto-table-cell-role="th">under5_mortality_rate</th>
<th data-quarto-table-cell-role="th">adolescent_fertility_rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">204</td>
<td>East Asia &amp; Pacific</td>
<td>2023</td>
<td>76.659477</td>
<td>14.5</td>
<td>14.565804</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">205</td>
<td>East Asia &amp; Pacific</td>
<td>2022</td>
<td>76.676784</td>
<td>14.7</td>
<td>14.800343</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">206</td>
<td>East Asia &amp; Pacific</td>
<td>2021</td>
<td>76.153009</td>
<td>14.9</td>
<td>15.197225</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">207</td>
<td>East Asia &amp; Pacific</td>
<td>2020</td>
<td>76.543438</td>
<td>14.9</td>
<td>15.878941</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">208</td>
<td>East Asia &amp; Pacific</td>
<td>2019</td>
<td>76.586262</td>
<td>14.8</td>
<td>17.261394</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The filtered dataset provides yearly health indicators for each region between 1990 and 2023, focusing on life expectancy, under-5 mortality rate, and adolescent fertility rate.</p>
</section>
<section id="life-expectancy-trends-over-time-19902023" class="level2">
<h2 class="anchored" data-anchor-id="life-expectancy-trends-over-time-19902023">Life Expectancy Trends Over Time (1990–2023)</h2>
<p>We visualized life expectancy trends across the seven major regions from 1990 to 2023. This helps identify the pace of health improvements over the past three decades.</p>
<div id="29ea0d13" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="QTM_350_Final_Project_files/figure-html/cell-4-output-1.png" width="1136" height="565" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>The resulting plot shows several key trends:</strong></p>
<ul>
<li><p><strong>Steady Gains Across All Regions</strong>: Life expectancy rose consistently in all regions, though at varying rates.</p></li>
<li><p><strong>Highest and Lowest</strong>: North America consistently maintained the highest life expectancy, while Sub-Saharan Africa started the period with the lowest but showed steady gains.</p></li>
<li><p><strong>Impact of External Events</strong>: Around 2020, there was a visible dip across several regions, likely due to the global COVID-19 pandemic’s impact on mortality.</p></li>
<li><p><strong>Narrowing Gaps</strong>: Regions such as East Asia &amp; Pacific and Europe &amp; Central Asia made notable progress, narrowing the life expectancy gap with North America by the end of the period.</p></li>
</ul>
<p>These trends provide important context for understanding population health improvements over time before diving into the detailed percent changes and associations with mortality and fertility rates.</p>
</section>
<section id="under-5-mortality-rate-trends-over-time-19902023" class="level2">
<h2 class="anchored" data-anchor-id="under-5-mortality-rate-trends-over-time-19902023">Under-5 Mortality Rate Trends Over Time (1990–2023)</h2>
<p>Next, we examined how under-5 mortality rates evolved across the same seven global regions from 1990 to 2023.</p>
<div id="56caa0a9" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="QTM_350_Final_Project_files/figure-html/cell-5-output-1.png" width="1135" height="565" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>The resulting figure reveals several important patterns:</strong></p>
<ul>
<li><p><strong>Universal Decline</strong>: Under-5 mortality rates dropped sharply in all regions between 1990 and 2023, reflecting broad improvements in child healthcare access and quality.</p></li>
<li><p><strong>Sub-Saharan Africa’s Progress</strong>: Despite starting with the highest child mortality rates, Sub-Saharan Africa achieved significant reductions over the period.</p></li>
<li><p><strong>South Asia’s Achievements</strong>: South Asia also demonstrated major progress, cutting under-5 mortality considerably.</p></li>
<li><p><strong>Consistently Low Rates:</strong> North America and Europe &amp; Central Asia maintained the lowest mortality rates throughout the period, highlighting robust healthcare infrastructures.</p></li>
<li><p><strong>Global Health Improvement</strong>: Overall, this figure underscores the global success in reducing childhood mortality rates over the past thirty years.</p></li>
</ul>
</section>
<section id="adolescent-fertility-rate-trends-over-time-19902023" class="level2">
<h2 class="anchored" data-anchor-id="adolescent-fertility-rate-trends-over-time-19902023">Adolescent Fertility Rate Trends Over Time (1990–2023)</h2>
<p>Finally, we analyzed how adolescent fertility rates evolved across regions between 1990 and 2023.</p>
<div id="3395e724" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="QTM_350_Final_Project_files/figure-html/cell-6-output-1.png" width="1135" height="565" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>The figure reveals:</strong></p>
<ul>
<li><p><strong>Widespread Decline</strong>: Adolescent fertility rates dropped sharply across all regions over the three decades.</p></li>
<li><p><strong>South Asia’s Success</strong>: South Asia, which initially had one of the highest adolescent fertility rates, demonstrated one of the steepest declines.</p></li>
<li><p><strong>Sub-Saharan Africa’s Progress</strong>: Sub-Saharan Africa also made progress but continues to exhibit relatively high adolescent fertility compared to other regions.</p></li>
<li><p><strong>Lower Rates in Developed Regions</strong>: North America and Europe &amp; Central Asia consistently maintained the lowest adolescent fertility rates, suggesting better access to education, reproductive health services, and empowerment initiatives for young women.</p></li>
<li><p><strong>Global Trend</strong>: Overall, the trends reflect major global improvements in healthcare, education, and socio-economic opportunities for adolescent women.</p></li>
</ul>
</section>
<section id="merging-1990-and-2023-data-for-regional-comparison" class="level2">
<h2 class="anchored" data-anchor-id="merging-1990-and-2023-data-for-regional-comparison">Merging 1990 and 2023 Data for Regional Comparison</h2>
<p>To assess long-term health improvements, we filtered the dataset to only include the years 1990 and 2023, and merged the two datasets by region for side-by-side comparison.</p>
<pre><code>&lt;IPython.core.display.Latex object&gt;</code></pre>
<p><strong>Explanation:</strong></p>
<ul>
<li><p>The filtering isolates records from 1990 and 2023.</p></li>
<li><p>We performed a merge on the country (region) column to align the two years side-by-side for each region.</p></li>
<li><p>This structure allows us to easily compute percentage changes in life expectancy, under-5 mortality, and adolescent fertility for each region.</p></li>
</ul>
<p>The merged dataset gives us the foundational structure needed to calculate improvements over time and to compare health trends between regions.</p>
<section id="calculating-percentage-changes-19902023" class="level4">
<h4 class="anchored" data-anchor-id="calculating-percentage-changes-19902023">Calculating Percentage Changes (1990–2023)</h4>
<p>To quantify improvements across health indicators, we calculated the percentage change for each region between 1990 and 2023 for:</p>
<ul>
<li><p>Life expectancy</p></li>
<li><p>Under-5 mortality rate</p></li>
<li><p>Adolescent fertility rate</p></li>
</ul>
<pre><code>&lt;IPython.core.display.Latex object&gt;</code></pre>
<p><br>
</p>
<p><strong>Key Insights:</strong></p>
<ul>
<li><p>Sub-Saharan Africa and South Asia recorded the fastest improvements in life expectancy, with gains of 25% and 23%, respectively.</p></li>
<li><p>North America showed the smallest life expectancy increase at just 4.4%, consistent with its already high baseline in 1990.</p></li>
<li><p>Under-5 mortality saw major declines across all regions, particularly in South Asia, East Asia &amp; Pacific, and Europe &amp; Central Asia, each with over 70% reductions.</p></li>
<li><p>In adolescent fertility, South Asia had the most dramatic improvement with an 81% decline, while North America and Europe &amp; Central Asia also showed strong declines of around 78% and 68%, respectively.</p></li>
</ul>
<p>This table offers a clear, side-by-side view of where health outcomes have improved most significantly over the past three decades.</p>
</section>
</section>
<section id="population-health-improvements-by-region-19902023" class="level2">
<h2 class="anchored" data-anchor-id="population-health-improvements-by-region-19902023">Population Health Improvements by Region (1990–2023)</h2>
<p>We calculated the percentage change in life expectancy, under-5 mortality, and adolescent fertility for each region between 1990 and 2023. The figure below shows a side-by-side comparison of improvements across these indicators.</p>
<div id="4964cb4d" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="QTM_350_Final_Project_files/figure-html/cell-9-output-1.png" width="1909" height="567" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong>:</p>
<ul>
<li><p>From 1990 to 2023, South Asia and Sub-Saharan Africa achieved the largest percentage increases in life expectancy and substantial reductions in under-5 mortality and adolescent fertility rates.</p></li>
<li><p>South Asia stands out for achieving the greatest overall gains across all three indicators, highlighting widespread improvements in health systems, education, and reproductive health.</p></li>
<li><p>Sub-Saharan Africa also showed meaningful improvements, although adolescent fertility remains relatively higher compared to other regions.</p></li>
<li><p>North America and Europe &amp; Central Asia experienced smaller relative gains in life expectancy, largely because they already had high health outcomes by 1990.</p></li>
<li><p>Notably, reductions in under-5 mortality were consistently strong across nearly all regions, showing the global success of child health interventions.</p></li>
</ul>
<p>This visualization highlights how regions that initially faced the most severe health challenges made the greatest strides over the past three decades.</p>
</section>
<section id="correlation-between-indicators" class="level2">
<h2 class="anchored" data-anchor-id="correlation-between-indicators">Correlation Between Indicators</h2>
<p>To better understand the relationships between improvements in life expectancy and the declines in under-5 mortality and adolescent fertility, we calculated Pearson correlation coefficients across regions.</p>
<div id="33bffffb" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Correlation between Life Expectancy Change and Under-5 Mortality Change: -0.364
Correlation between Life Expectancy Change and Adolescent Fertility Change: 0.388</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>:</p>
<ul>
<li><p>The correlation between life expectancy change and under-5 mortality rate change was moderately negative (r = -0.364).</p>
<p>This suggests that regions with greater reductions in child mortality tended to experience larger gains in life expectancy. However, the relationship is not extremely strong, implying that while child survival improvements contribute meaningfully to longer life spans, other factors (such as adult health and socioeconomic conditions) also play a role.</p></li>
<li><p>The correlation between life expectancy change and adolescent fertility rate change was moderately positive (r = 0.388).</p>
<p>This indicates that regions with sharper declines in adolescent fertility tended to achieve larger gains in life expectancy. While the association is noticeable, it is moderate, suggesting that improvements in adolescent reproductive health likely support but do not solely drive broader health improvements.</p></li>
</ul>
</section>
<section id="deeper-scatterplot-analysis" class="level2">
<h2 class="anchored" data-anchor-id="deeper-scatterplot-analysis">Deeper Scatterplot Analysis</h2>
<p>To further visualize and support our correlation findings, we produced detailed scatterplots:</p>
<ul>
<li><p>Life Expectancy vs Under-5 Mortality Improvements</p></li>
<li><p>Life Expectancy vs Adolescent Fertility Improvements</p></li>
</ul>
<div id="25265ae9" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="QTM_350_Final_Project_files/figure-html/cell-11-output-1.png" width="659" height="528" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="QTM_350_Final_Project_files/figure-html/cell-11-output-2.png" width="659" height="528" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Life Expectancy vs.&nbsp;Under-5 Mortality Improvements:</strong></p>
<ul>
<li><p>The scatter plot shows a moderate negative relationship between reductions in under-5 mortality and improvements in life expectancy (r = -0.36).</p></li>
<li><p>Regions like South Asia and Sub-Saharan Africa that achieved larger declines in child mortality generally saw greater gains in life expectancy.</p></li>
<li><p>North America appears as an outlier with relatively high life expectancy but smaller reductions in under-5 mortality, reflecting its already strong baseline by 1990.</p></li>
</ul>
<p><strong>Life Expectancy vs.&nbsp;Adolescent Fertility Improvements:</strong></p>
<ul>
<li><p>The scatter plot shows a moderate positive relationship between reductions in adolescent fertility and life expectancy gains (r = 0.39).</p></li>
<li><p>Regions with sharper declines in teenage birth rates, such as South Asia and Sub-Saharan Africa, tended to experience larger life expectancy improvements.</p></li>
<li><p>The upward trend suggests that improvements in reproductive health outcomes contribute meaningfully to broader population health progress.</p></li>
</ul>
<p><strong>Key Takeaways from the Scatterplots:</strong></p>
<ul>
<li><p>Although both child mortality and adolescent fertility reductions are associated with life expectancy gains, the relationships are moderate rather than extremely strong.</p></li>
<li><p>This highlights that multiple social, economic, and healthcare factors simultaneously influence health improvements across regions.</p></li>
<li><p>Regions starting from worse initial conditions (lower life expectancy, higher child mortality) generally made the most rapid relative progress over the past three decades.</p></li>
</ul>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="summary-of-main-findings" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-main-findings">Summary of Main Findings</h2>
<p>Our analysis highlights striking patterns in global health progress between 1990 and 2023. Across all three indicators—life expectancy, under-5 mortality, and adolescent fertility—substantial improvements were observed, but the pace and magnitude of change varied meaningfully by region.</p>
<ul>
<li><p>Sub-Saharan Africa and South Asia exhibited the most remarkable health gains overall. Sub-Saharan Africa achieved the highest percentage increase in life expectancy (25.1%) despite starting from the lowest baseline, coupled with a notable 62% reduction in under-5 mortality and a 32% reduction in adolescent fertility rates. South Asia followed closely, recording a 22.6% rise in life expectancy, a 73% drop in under-5 mortality, and an outstanding 81% decline in adolescent fertility. These results reflect the region’s substantial efforts in expanding healthcare access, improving maternal and child health, and investing in education for young women.</p></li>
<li><p>North America and Europe &amp; Central Asia maintained relatively high baseline health levels throughout the period. Although they showed smaller relative improvements in life expectancy (only 4–9% increases), they consistently had the lowest under-5 mortality and adolescent fertility rates both in 1990 and 2023. North America, in particular, experienced a significant 78% drop in adolescent fertility, underscoring continued progress in reproductive health services despite a modest increase in life expectancy.</p></li>
<li><p>Latin America &amp; the Caribbean and the Middle East &amp; North Africa demonstrated intermediate patterns, achieving around 12–16% increases in life expectancy while simultaneously making major strides in reducing child and adolescent health risks.</p></li>
</ul>
<p>Our comparative barplots vividly illustrate that regions with lower initial health outcomes in 1990 made the largest relative improvements by 2023, suggesting a global convergence trend in population health. However, the data also shows that some disparities persist, especially regarding adolescent fertility and child mortality in Sub-Saharan Africa.</p>
</section>
<section id="discussion-of-limitations" class="level2">
<h2 class="anchored" data-anchor-id="discussion-of-limitations">Discussion of Limitations</h2>
<ul>
<li><p><strong>Temporal Aggregation and Measurement Gaps</strong>: While we tracked health changes over a 33-year period (1990–2023), year-to-year variations and shorter-term health shocks are smoothed over in our analysis. Important events—such as political instability, disease outbreaks, or healthcare reforms—may have caused temporary deviations that are not fully captured when looking only at start and end points.</p></li>
<li><p><strong>Regional Aggregation Effects</strong>: Aggregating diverse countries into broader regions may obscure important within-region differences. For instance, life expectancy trends in South Asia may differ significantly between countries like India and Bangladesh.</p></li>
<li><p><strong>Correlation Limitations:</strong> Correlation does not imply causality. Although strong associations between indicators were found, we cannot definitively conclude that reductions in under-5 mortality or adolescent fertility caused increases in life expectancy.</p></li>
<li><p><strong>External Shocks:</strong> Events like the COVID-19 pandemic likely disrupted some health trends, particularly post-2020, but our model does not account for such shocks explicitly.</p></li>
</ul>
</section>
</section>
<section id="further-reading" class="level1">
<h1>Further Reading</h1>
<p>To support our analysis and ensure reproducibility, we used the following resources:</p>
<p><a href="https://data.worldbank.org/indicator">World Bank Data - Indicators</a></p>
<p>(Source for life expectancy, under-5 mortality, and adolescent fertility rates)</p>
<p><a href="https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation">World Bank API Documentation</a></p>
<p>(Used for programmatically pulling health data into Python)</p>
<p><a href="https://databank.worldbank.org/source/world-development-indicators#">World Development Indicators - World Bank</a></p>
<p>(Background information on global health and socioeconomic trends)</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>